/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IHM;

import Client.ChatClient;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author martingermain
 */
public class ChatLoginUI extends javax.swing.JFrame {
    
    private ChatClient client = new ChatClient();
    
    /**
     * Creates new form ChatLoginUI
     */
    public ChatLoginUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackScreen = new javax.swing.JPanel();
        jLabelHeader = new javax.swing.JLabel();
        jSeparatorAdress = new javax.swing.JSeparator();
        jSeparatorPort = new javax.swing.JSeparator();
        IconAdress = new javax.swing.JLabel();
        IconPort = new javax.swing.JLabel();
        jLabelAdress = new javax.swing.JLabel();
        jLabelPort = new javax.swing.JLabel();
        jTPort = new javax.swing.JTextField();
        jSeparatorUsername = new javax.swing.JSeparator();
        IconUser = new javax.swing.JLabel();
        jLabelUsername = new javax.swing.JLabel();
        jBJoin = new javax.swing.JButton();
        jTUsername = new javax.swing.JTextField();
        jTAddress = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Project Chat Login");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        BackScreen.setBackground(new java.awt.Color(255, 255, 255));
        BackScreen.setToolTipText("");
        BackScreen.setName(""); // NOI18N
        BackScreen.setPreferredSize(new java.awt.Dimension(455, 550));

        jLabelHeader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/HeaderBanner.png"))); // NOI18N
        jLabelHeader.setToolTipText("");

        jSeparatorAdress.setForeground(new java.awt.Color(77, 180, 180));

        jSeparatorPort.setForeground(new java.awt.Color(77, 180, 180));

        IconAdress.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Adress.png"))); // NOI18N
        IconAdress.setToolTipText("");

        IconPort.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Port.png"))); // NOI18N
        IconPort.setToolTipText("");

        jLabelAdress.setFont(new java.awt.Font("PingFang TC", 1, 24)); // NOI18N
        jLabelAdress.setForeground(new java.awt.Color(77, 180, 180));
        jLabelAdress.setText("Adress:");

        jLabelPort.setFont(new java.awt.Font("PingFang TC", 1, 24)); // NOI18N
        jLabelPort.setForeground(new java.awt.Color(77, 180, 180));
        jLabelPort.setText("Port:");

        jTPort.setFont(new java.awt.Font("PingFang TC", 0, 18)); // NOI18N
        jTPort.setForeground(new java.awt.Color(77, 180, 180));
        jTPort.setToolTipText("");
        jTPort.setBorder(null);
        jTPort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTPortActionPerformed(evt);
            }
        });

        jSeparatorUsername.setForeground(new java.awt.Color(77, 180, 180));

        IconUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/User.png"))); // NOI18N
        IconUser.setToolTipText("");

        jLabelUsername.setFont(new java.awt.Font("PingFang TC", 1, 24)); // NOI18N
        jLabelUsername.setForeground(new java.awt.Color(77, 180, 180));
        jLabelUsername.setText("Username:");

        jBJoin.setBackground(new java.awt.Color(255, 255, 255));
        jBJoin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Valider.png"))); // NOI18N
        jBJoin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jBJoin.setBorderPainted(false);
        jBJoin.setContentAreaFilled(false);
        jBJoin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBJoin.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jBJoinMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jBJoinMouseMoved(evt);
            }
        });
        jBJoin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBJoinMouseClicked(evt);
            }
        });

        jTUsername.setFont(new java.awt.Font("PingFang TC", 0, 18)); // NOI18N
        jTUsername.setForeground(new java.awt.Color(77, 180, 180));
        jTUsername.setToolTipText("");
        jTUsername.setBorder(null);
        jTUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTUsernameActionPerformed(evt);
            }
        });

        jTAddress.setFont(new java.awt.Font("PingFang TC", 0, 18)); // NOI18N
        jTAddress.setForeground(new java.awt.Color(77, 180, 180));
        jTAddress.setToolTipText("");
        jTAddress.setBorder(null);
        jTAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTAddressActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BackScreenLayout = new javax.swing.GroupLayout(BackScreen);
        BackScreen.setLayout(BackScreenLayout);
        BackScreenLayout.setHorizontalGroup(
            BackScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelHeader, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(BackScreenLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(BackScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackScreenLayout.createSequentialGroup()
                        .addGroup(BackScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparatorUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(BackScreenLayout.createSequentialGroup()
                                .addComponent(IconUser, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                        .addComponent(jBJoin, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(BackScreenLayout.createSequentialGroup()
                        .addGroup(BackScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BackScreenLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jTPort, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelAdress)
                            .addComponent(jSeparatorPort, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IconPort, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPort)
                            .addComponent(jLabelUsername)
                            .addGroup(BackScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, BackScreenLayout.createSequentialGroup()
                                    .addComponent(IconAdress, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jSeparatorAdress, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        BackScreenLayout.setVerticalGroup(
            BackScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackScreenLayout.createSequentialGroup()
                .addComponent(jLabelHeader)
                .addGap(12, 12, 12)
                .addGroup(BackScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackScreenLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(IconAdress, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BackScreenLayout.createSequentialGroup()
                        .addGroup(BackScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BackScreenLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(BackScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(BackScreenLayout.createSequentialGroup()
                                        .addGap(60, 60, 60)
                                        .addComponent(jLabelAdress))
                                    .addGroup(BackScreenLayout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addComponent(jSeparatorPort, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(IconPort, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabelPort)
                            .addGroup(BackScreenLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jTPort, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jSeparatorAdress, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 220, Short.MAX_VALUE)
                .addGroup(BackScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackScreenLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(IconUser, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BackScreenLayout.createSequentialGroup()
                        .addComponent(jLabelUsername)
                        .addGap(5, 5, 5)
                        .addGroup(BackScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BackScreenLayout.createSequentialGroup()
                                .addComponent(jTUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(jSeparatorUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jBJoin))))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackScreen, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BackScreen, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Start the Chat when the user clicks on the Valider Button
     * Get the Address, port, Username to connect to the server
     * 
     * @param evt MouseEvent
     * 
     */
    private void jBJoinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBJoinMouseClicked
        client.connectToServer(jTAddress.getText(),jTPort.getText(),jTUsername.getText());
        this.dispose();
    }//GEN-LAST:event_jBJoinMouseClicked

    private void jBJoinMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBJoinMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jBJoinMouseMoved

    private void jBJoinMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBJoinMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_jBJoinMouseDragged

    private void jTPortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTPortActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTPortActionPerformed

    private void jTUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTUsernameActionPerformed

    private void jTAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTAddressActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChatLoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChatLoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChatLoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChatLoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChatLoginUI().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackScreen;
    private javax.swing.JLabel IconAdress;
    private javax.swing.JLabel IconPort;
    private javax.swing.JLabel IconUser;
    private javax.swing.JButton jBJoin;
    private javax.swing.JLabel jLabelAdress;
    private javax.swing.JLabel jLabelHeader;
    private javax.swing.JLabel jLabelPort;
    private javax.swing.JLabel jLabelUsername;
    private javax.swing.JSeparator jSeparatorAdress;
    private javax.swing.JSeparator jSeparatorPort;
    private javax.swing.JSeparator jSeparatorUsername;
    private javax.swing.JTextField jTAddress;
    private javax.swing.JTextField jTPort;
    private javax.swing.JTextField jTUsername;
    // End of variables declaration//GEN-END:variables
}

